
//
// DO NOT EDIT THIS CODE
//
// It was automatically generated 
//   by: generate_vectorn_swizzles.py
//   at: 2013-04-14 18:53:06
//


#define VECTORN_SWIZZLE_(func, i1, i2)\
VectorN<base_t, 2>\
func()\
{\
  return VectorN<base_t, 2> (v[i1], v[i2]);\
}

VECTORN_SWIZZLE_( xx , 0 , 0 )
VECTORN_SWIZZLE_( xy , 0 , 1 )
VECTORN_SWIZZLE_( yx , 1 , 0 )
VECTORN_SWIZZLE_( yy , 1 , 1 )

#undef VECTORN_SWIZZLE_


#define VECTORN_SWIZZLE_(func, i1, i2, i3)\
VectorN<base_t, 3>\
func()\
{\
  static_assert(N >= 3,\
    "can't use swizzle " #func  "() on VectorN<base_t, N> with N<3"); \
  return VectorN<base_t, 3> (v[i1], v[i2], v[i3]);\
}

VECTORN_SWIZZLE_( xxx , 0 , 0 , 0 )
VECTORN_SWIZZLE_( xxy , 0 , 0 , 1 )
VECTORN_SWIZZLE_( xxz , 0 , 0 , 2 )
VECTORN_SWIZZLE_( xyx , 0 , 1 , 0 )
VECTORN_SWIZZLE_( xyy , 0 , 1 , 1 )
VECTORN_SWIZZLE_( xyz , 0 , 1 , 2 )
VECTORN_SWIZZLE_( xzx , 0 , 2 , 0 )
VECTORN_SWIZZLE_( xzy , 0 , 2 , 1 )
VECTORN_SWIZZLE_( xzz , 0 , 2 , 2 )
VECTORN_SWIZZLE_( yxx , 1 , 0 , 0 )
VECTORN_SWIZZLE_( yxy , 1 , 0 , 1 )
VECTORN_SWIZZLE_( yxz , 1 , 0 , 2 )
VECTORN_SWIZZLE_( yyx , 1 , 1 , 0 )
VECTORN_SWIZZLE_( yyy , 1 , 1 , 1 )
VECTORN_SWIZZLE_( yyz , 1 , 1 , 2 )
VECTORN_SWIZZLE_( yzx , 1 , 2 , 0 )
VECTORN_SWIZZLE_( yzy , 1 , 2 , 1 )
VECTORN_SWIZZLE_( yzz , 1 , 2 , 2 )
VECTORN_SWIZZLE_( zxx , 2 , 0 , 0 )
VECTORN_SWIZZLE_( zxy , 2 , 0 , 1 )
VECTORN_SWIZZLE_( zxz , 2 , 0 , 2 )
VECTORN_SWIZZLE_( zyx , 2 , 1 , 0 )
VECTORN_SWIZZLE_( zyy , 2 , 1 , 1 )
VECTORN_SWIZZLE_( zyz , 2 , 1 , 2 )
VECTORN_SWIZZLE_( zzx , 2 , 2 , 0 )
VECTORN_SWIZZLE_( zzy , 2 , 2 , 1 )
VECTORN_SWIZZLE_( zzz , 2 , 2 , 2 )

#undef VECTORN_SWIZZLE_


#define VECTORN_SWIZZLE_(func, i1, i2, i3, i4)\
VectorN<base_t, 4>\
func()\
{\
  static_assert(N >= 4,\
    "can't use swizzle " #func  "() on VectorN<base_t, N> with N<4"); \
  return VectorN<base_t, 4> (v[i1], v[i2], v[i3], v[i4]);\
}

VECTORN_SWIZZLE_( xxxx , 0 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( xxxy , 0 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( xxxz , 0 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( xxxw , 0 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( xxyx , 0 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( xxyy , 0 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( xxyz , 0 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( xxyw , 0 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( xxzx , 0 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( xxzy , 0 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( xxzz , 0 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( xxzw , 0 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( xxwx , 0 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( xxwy , 0 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( xxwz , 0 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( xxww , 0 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( xyxx , 0 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( xyxy , 0 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( xyxz , 0 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( xyxw , 0 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( xyyx , 0 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( xyyy , 0 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( xyyz , 0 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( xyyw , 0 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( xyzx , 0 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( xyzy , 0 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( xyzz , 0 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( xyzw , 0 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( xywx , 0 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( xywy , 0 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( xywz , 0 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( xyww , 0 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( xzxx , 0 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( xzxy , 0 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( xzxz , 0 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( xzxw , 0 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( xzyx , 0 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( xzyy , 0 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( xzyz , 0 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( xzyw , 0 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( xzzx , 0 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( xzzy , 0 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( xzzz , 0 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( xzzw , 0 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( xzwx , 0 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( xzwy , 0 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( xzwz , 0 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( xzww , 0 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( xwxx , 0 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( xwxy , 0 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( xwxz , 0 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( xwxw , 0 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( xwyx , 0 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( xwyy , 0 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( xwyz , 0 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( xwyw , 0 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( xwzx , 0 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( xwzy , 0 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( xwzz , 0 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( xwzw , 0 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( xwwx , 0 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( xwwy , 0 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( xwwz , 0 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( xwww , 0 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( yxxx , 1 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( yxxy , 1 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( yxxz , 1 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( yxxw , 1 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( yxyx , 1 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( yxyy , 1 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( yxyz , 1 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( yxyw , 1 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( yxzx , 1 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( yxzy , 1 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( yxzz , 1 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( yxzw , 1 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( yxwx , 1 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( yxwy , 1 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( yxwz , 1 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( yxww , 1 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( yyxx , 1 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( yyxy , 1 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( yyxz , 1 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( yyxw , 1 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( yyyx , 1 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( yyyy , 1 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( yyyz , 1 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( yyyw , 1 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( yyzx , 1 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( yyzy , 1 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( yyzz , 1 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( yyzw , 1 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( yywx , 1 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( yywy , 1 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( yywz , 1 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( yyww , 1 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( yzxx , 1 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( yzxy , 1 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( yzxz , 1 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( yzxw , 1 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( yzyx , 1 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( yzyy , 1 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( yzyz , 1 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( yzyw , 1 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( yzzx , 1 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( yzzy , 1 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( yzzz , 1 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( yzzw , 1 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( yzwx , 1 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( yzwy , 1 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( yzwz , 1 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( yzww , 1 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( ywxx , 1 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( ywxy , 1 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( ywxz , 1 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( ywxw , 1 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( ywyx , 1 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( ywyy , 1 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( ywyz , 1 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( ywyw , 1 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( ywzx , 1 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( ywzy , 1 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( ywzz , 1 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( ywzw , 1 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( ywwx , 1 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( ywwy , 1 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( ywwz , 1 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( ywww , 1 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( zxxx , 2 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( zxxy , 2 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( zxxz , 2 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( zxxw , 2 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( zxyx , 2 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( zxyy , 2 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( zxyz , 2 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( zxyw , 2 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( zxzx , 2 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( zxzy , 2 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( zxzz , 2 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( zxzw , 2 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( zxwx , 2 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( zxwy , 2 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( zxwz , 2 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( zxww , 2 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( zyxx , 2 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( zyxy , 2 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( zyxz , 2 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( zyxw , 2 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( zyyx , 2 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( zyyy , 2 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( zyyz , 2 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( zyyw , 2 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( zyzx , 2 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( zyzy , 2 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( zyzz , 2 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( zyzw , 2 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( zywx , 2 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( zywy , 2 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( zywz , 2 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( zyww , 2 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( zzxx , 2 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( zzxy , 2 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( zzxz , 2 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( zzxw , 2 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( zzyx , 2 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( zzyy , 2 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( zzyz , 2 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( zzyw , 2 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( zzzx , 2 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( zzzy , 2 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( zzzz , 2 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( zzzw , 2 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( zzwx , 2 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( zzwy , 2 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( zzwz , 2 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( zzww , 2 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( zwxx , 2 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( zwxy , 2 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( zwxz , 2 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( zwxw , 2 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( zwyx , 2 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( zwyy , 2 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( zwyz , 2 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( zwyw , 2 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( zwzx , 2 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( zwzy , 2 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( zwzz , 2 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( zwzw , 2 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( zwwx , 2 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( zwwy , 2 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( zwwz , 2 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( zwww , 2 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( wxxx , 3 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( wxxy , 3 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( wxxz , 3 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( wxxw , 3 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( wxyx , 3 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( wxyy , 3 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( wxyz , 3 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( wxyw , 3 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( wxzx , 3 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( wxzy , 3 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( wxzz , 3 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( wxzw , 3 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( wxwx , 3 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( wxwy , 3 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( wxwz , 3 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( wxww , 3 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( wyxx , 3 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( wyxy , 3 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( wyxz , 3 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( wyxw , 3 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( wyyx , 3 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( wyyy , 3 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( wyyz , 3 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( wyyw , 3 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( wyzx , 3 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( wyzy , 3 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( wyzz , 3 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( wyzw , 3 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( wywx , 3 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( wywy , 3 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( wywz , 3 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( wyww , 3 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( wzxx , 3 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( wzxy , 3 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( wzxz , 3 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( wzxw , 3 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( wzyx , 3 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( wzyy , 3 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( wzyz , 3 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( wzyw , 3 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( wzzx , 3 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( wzzy , 3 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( wzzz , 3 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( wzzw , 3 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( wzwx , 3 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( wzwy , 3 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( wzwz , 3 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( wzww , 3 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( wwxx , 3 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( wwxy , 3 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( wwxz , 3 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( wwxw , 3 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( wwyx , 3 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( wwyy , 3 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( wwyz , 3 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( wwyw , 3 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( wwzx , 3 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( wwzy , 3 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( wwzz , 3 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( wwzw , 3 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( wwwx , 3 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( wwwy , 3 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( wwwz , 3 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( wwww , 3 , 3 , 3 , 3 )

#undef VECTORN_SWIZZLE_


#define VECTORN_SWIZZLE_(func, i1, i2)\
VectorN<base_t, 2>\
func()\
{\
  return VectorN<base_t, 2> (v[i1], v[i2]);\
}

VECTORN_SWIZZLE_( rr , 0 , 0 )
VECTORN_SWIZZLE_( rg , 0 , 1 )
VECTORN_SWIZZLE_( gr , 1 , 0 )
VECTORN_SWIZZLE_( gg , 1 , 1 )

#undef VECTORN_SWIZZLE_


#define VECTORN_SWIZZLE_(func, i1, i2, i3)\
VectorN<base_t, 3>\
func()\
{\
  static_assert(N >= 3,\
    "can't use swizzle " #func  "() on VectorN<base_t, N> with N<3"); \
  return VectorN<base_t, 3> (v[i1], v[i2], v[i3]);\
}

VECTORN_SWIZZLE_( rrr , 0 , 0 , 0 )
VECTORN_SWIZZLE_( rrg , 0 , 0 , 1 )
VECTORN_SWIZZLE_( rrb , 0 , 0 , 2 )
VECTORN_SWIZZLE_( rgr , 0 , 1 , 0 )
VECTORN_SWIZZLE_( rgg , 0 , 1 , 1 )
VECTORN_SWIZZLE_( rgb , 0 , 1 , 2 )
VECTORN_SWIZZLE_( rbr , 0 , 2 , 0 )
VECTORN_SWIZZLE_( rbg , 0 , 2 , 1 )
VECTORN_SWIZZLE_( rbb , 0 , 2 , 2 )
VECTORN_SWIZZLE_( grr , 1 , 0 , 0 )
VECTORN_SWIZZLE_( grg , 1 , 0 , 1 )
VECTORN_SWIZZLE_( grb , 1 , 0 , 2 )
VECTORN_SWIZZLE_( ggr , 1 , 1 , 0 )
VECTORN_SWIZZLE_( ggg , 1 , 1 , 1 )
VECTORN_SWIZZLE_( ggb , 1 , 1 , 2 )
VECTORN_SWIZZLE_( gbr , 1 , 2 , 0 )
VECTORN_SWIZZLE_( gbg , 1 , 2 , 1 )
VECTORN_SWIZZLE_( gbb , 1 , 2 , 2 )
VECTORN_SWIZZLE_( brr , 2 , 0 , 0 )
VECTORN_SWIZZLE_( brg , 2 , 0 , 1 )
VECTORN_SWIZZLE_( brb , 2 , 0 , 2 )
VECTORN_SWIZZLE_( bgr , 2 , 1 , 0 )
VECTORN_SWIZZLE_( bgg , 2 , 1 , 1 )
VECTORN_SWIZZLE_( bgb , 2 , 1 , 2 )
VECTORN_SWIZZLE_( bbr , 2 , 2 , 0 )
VECTORN_SWIZZLE_( bbg , 2 , 2 , 1 )
VECTORN_SWIZZLE_( bbb , 2 , 2 , 2 )

#undef VECTORN_SWIZZLE_


#define VECTORN_SWIZZLE_(func, i1, i2, i3, i4)\
VectorN<base_t, 4>\
func()\
{\
  static_assert(N >= 4,\
    "can't use swizzle " #func  "() on VectorN<base_t, N> with N<4"); \
  return VectorN<base_t, 4> (v[i1], v[i2], v[i3], v[i4]);\
}

VECTORN_SWIZZLE_( rrrr , 0 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( rrrg , 0 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( rrrb , 0 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( rrra , 0 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( rrgr , 0 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( rrgg , 0 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( rrgb , 0 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( rrga , 0 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( rrbr , 0 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( rrbg , 0 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( rrbb , 0 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( rrba , 0 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( rrar , 0 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( rrag , 0 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( rrab , 0 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( rraa , 0 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( rgrr , 0 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( rgrg , 0 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( rgrb , 0 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( rgra , 0 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( rggr , 0 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( rggg , 0 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( rggb , 0 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( rgga , 0 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( rgbr , 0 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( rgbg , 0 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( rgbb , 0 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( rgba , 0 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( rgar , 0 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( rgag , 0 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( rgab , 0 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( rgaa , 0 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( rbrr , 0 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( rbrg , 0 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( rbrb , 0 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( rbra , 0 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( rbgr , 0 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( rbgg , 0 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( rbgb , 0 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( rbga , 0 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( rbbr , 0 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( rbbg , 0 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( rbbb , 0 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( rbba , 0 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( rbar , 0 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( rbag , 0 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( rbab , 0 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( rbaa , 0 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( rarr , 0 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( rarg , 0 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( rarb , 0 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( rara , 0 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( ragr , 0 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( ragg , 0 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( ragb , 0 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( raga , 0 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( rabr , 0 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( rabg , 0 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( rabb , 0 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( raba , 0 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( raar , 0 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( raag , 0 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( raab , 0 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( raaa , 0 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( grrr , 1 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( grrg , 1 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( grrb , 1 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( grra , 1 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( grgr , 1 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( grgg , 1 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( grgb , 1 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( grga , 1 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( grbr , 1 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( grbg , 1 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( grbb , 1 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( grba , 1 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( grar , 1 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( grag , 1 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( grab , 1 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( graa , 1 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( ggrr , 1 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( ggrg , 1 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( ggrb , 1 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( ggra , 1 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( gggr , 1 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( gggg , 1 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( gggb , 1 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( ggga , 1 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( ggbr , 1 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( ggbg , 1 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( ggbb , 1 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( ggba , 1 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( ggar , 1 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( ggag , 1 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( ggab , 1 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( ggaa , 1 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( gbrr , 1 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( gbrg , 1 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( gbrb , 1 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( gbra , 1 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( gbgr , 1 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( gbgg , 1 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( gbgb , 1 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( gbga , 1 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( gbbr , 1 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( gbbg , 1 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( gbbb , 1 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( gbba , 1 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( gbar , 1 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( gbag , 1 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( gbab , 1 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( gbaa , 1 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( garr , 1 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( garg , 1 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( garb , 1 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( gara , 1 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( gagr , 1 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( gagg , 1 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( gagb , 1 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( gaga , 1 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( gabr , 1 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( gabg , 1 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( gabb , 1 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( gaba , 1 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( gaar , 1 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( gaag , 1 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( gaab , 1 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( gaaa , 1 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( brrr , 2 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( brrg , 2 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( brrb , 2 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( brra , 2 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( brgr , 2 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( brgg , 2 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( brgb , 2 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( brga , 2 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( brbr , 2 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( brbg , 2 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( brbb , 2 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( brba , 2 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( brar , 2 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( brag , 2 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( brab , 2 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( braa , 2 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( bgrr , 2 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( bgrg , 2 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( bgrb , 2 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( bgra , 2 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( bggr , 2 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( bggg , 2 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( bggb , 2 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( bgga , 2 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( bgbr , 2 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( bgbg , 2 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( bgbb , 2 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( bgba , 2 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( bgar , 2 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( bgag , 2 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( bgab , 2 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( bgaa , 2 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( bbrr , 2 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( bbrg , 2 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( bbrb , 2 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( bbra , 2 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( bbgr , 2 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( bbgg , 2 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( bbgb , 2 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( bbga , 2 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( bbbr , 2 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( bbbg , 2 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( bbbb , 2 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( bbba , 2 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( bbar , 2 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( bbag , 2 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( bbab , 2 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( bbaa , 2 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( barr , 2 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( barg , 2 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( barb , 2 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( bara , 2 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( bagr , 2 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( bagg , 2 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( bagb , 2 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( baga , 2 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( babr , 2 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( babg , 2 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( babb , 2 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( baba , 2 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( baar , 2 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( baag , 2 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( baab , 2 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( baaa , 2 , 3 , 3 , 3 )
VECTORN_SWIZZLE_( arrr , 3 , 0 , 0 , 0 )
VECTORN_SWIZZLE_( arrg , 3 , 0 , 0 , 1 )
VECTORN_SWIZZLE_( arrb , 3 , 0 , 0 , 2 )
VECTORN_SWIZZLE_( arra , 3 , 0 , 0 , 3 )
VECTORN_SWIZZLE_( argr , 3 , 0 , 1 , 0 )
VECTORN_SWIZZLE_( argg , 3 , 0 , 1 , 1 )
VECTORN_SWIZZLE_( argb , 3 , 0 , 1 , 2 )
VECTORN_SWIZZLE_( arga , 3 , 0 , 1 , 3 )
VECTORN_SWIZZLE_( arbr , 3 , 0 , 2 , 0 )
VECTORN_SWIZZLE_( arbg , 3 , 0 , 2 , 1 )
VECTORN_SWIZZLE_( arbb , 3 , 0 , 2 , 2 )
VECTORN_SWIZZLE_( arba , 3 , 0 , 2 , 3 )
VECTORN_SWIZZLE_( arar , 3 , 0 , 3 , 0 )
VECTORN_SWIZZLE_( arag , 3 , 0 , 3 , 1 )
VECTORN_SWIZZLE_( arab , 3 , 0 , 3 , 2 )
VECTORN_SWIZZLE_( araa , 3 , 0 , 3 , 3 )
VECTORN_SWIZZLE_( agrr , 3 , 1 , 0 , 0 )
VECTORN_SWIZZLE_( agrg , 3 , 1 , 0 , 1 )
VECTORN_SWIZZLE_( agrb , 3 , 1 , 0 , 2 )
VECTORN_SWIZZLE_( agra , 3 , 1 , 0 , 3 )
VECTORN_SWIZZLE_( aggr , 3 , 1 , 1 , 0 )
VECTORN_SWIZZLE_( aggg , 3 , 1 , 1 , 1 )
VECTORN_SWIZZLE_( aggb , 3 , 1 , 1 , 2 )
VECTORN_SWIZZLE_( agga , 3 , 1 , 1 , 3 )
VECTORN_SWIZZLE_( agbr , 3 , 1 , 2 , 0 )
VECTORN_SWIZZLE_( agbg , 3 , 1 , 2 , 1 )
VECTORN_SWIZZLE_( agbb , 3 , 1 , 2 , 2 )
VECTORN_SWIZZLE_( agba , 3 , 1 , 2 , 3 )
VECTORN_SWIZZLE_( agar , 3 , 1 , 3 , 0 )
VECTORN_SWIZZLE_( agag , 3 , 1 , 3 , 1 )
VECTORN_SWIZZLE_( agab , 3 , 1 , 3 , 2 )
VECTORN_SWIZZLE_( agaa , 3 , 1 , 3 , 3 )
VECTORN_SWIZZLE_( abrr , 3 , 2 , 0 , 0 )
VECTORN_SWIZZLE_( abrg , 3 , 2 , 0 , 1 )
VECTORN_SWIZZLE_( abrb , 3 , 2 , 0 , 2 )
VECTORN_SWIZZLE_( abra , 3 , 2 , 0 , 3 )
VECTORN_SWIZZLE_( abgr , 3 , 2 , 1 , 0 )
VECTORN_SWIZZLE_( abgg , 3 , 2 , 1 , 1 )
VECTORN_SWIZZLE_( abgb , 3 , 2 , 1 , 2 )
VECTORN_SWIZZLE_( abga , 3 , 2 , 1 , 3 )
VECTORN_SWIZZLE_( abbr , 3 , 2 , 2 , 0 )
VECTORN_SWIZZLE_( abbg , 3 , 2 , 2 , 1 )
VECTORN_SWIZZLE_( abbb , 3 , 2 , 2 , 2 )
VECTORN_SWIZZLE_( abba , 3 , 2 , 2 , 3 )
VECTORN_SWIZZLE_( abar , 3 , 2 , 3 , 0 )
VECTORN_SWIZZLE_( abag , 3 , 2 , 3 , 1 )
VECTORN_SWIZZLE_( abab , 3 , 2 , 3 , 2 )
VECTORN_SWIZZLE_( abaa , 3 , 2 , 3 , 3 )
VECTORN_SWIZZLE_( aarr , 3 , 3 , 0 , 0 )
VECTORN_SWIZZLE_( aarg , 3 , 3 , 0 , 1 )
VECTORN_SWIZZLE_( aarb , 3 , 3 , 0 , 2 )
VECTORN_SWIZZLE_( aara , 3 , 3 , 0 , 3 )
VECTORN_SWIZZLE_( aagr , 3 , 3 , 1 , 0 )
VECTORN_SWIZZLE_( aagg , 3 , 3 , 1 , 1 )
VECTORN_SWIZZLE_( aagb , 3 , 3 , 1 , 2 )
VECTORN_SWIZZLE_( aaga , 3 , 3 , 1 , 3 )
VECTORN_SWIZZLE_( aabr , 3 , 3 , 2 , 0 )
VECTORN_SWIZZLE_( aabg , 3 , 3 , 2 , 1 )
VECTORN_SWIZZLE_( aabb , 3 , 3 , 2 , 2 )
VECTORN_SWIZZLE_( aaba , 3 , 3 , 2 , 3 )
VECTORN_SWIZZLE_( aaar , 3 , 3 , 3 , 0 )
VECTORN_SWIZZLE_( aaag , 3 , 3 , 3 , 1 )
VECTORN_SWIZZLE_( aaab , 3 , 3 , 3 , 2 )
VECTORN_SWIZZLE_( aaaa , 3 , 3 , 3 , 3 )

#undef VECTORN_SWIZZLE_

